version: '3.7'

networks:
  application:
    # a bridge network allows containers connect to the same bridge network to communicate while preventing other containers to
    # reach the network.
    # Note: bridge network creates a network to connect with hostnames.
    driver: bridge