server:
  port: 8888

# logging level can override logback logging properties(defined in logback.xml) in application config
logging:
  level:
    ROOT: INFO
    org.spring.framework.cloud.config: DEBUG