server:
  port: 8888

# logging level can override logback logging properties(defined in logback.xml) in application config
logging:
  level:
    ROOT: DEBUG
    org.spring.framework.cloud.config: DEBUG

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        git:
          #          uri: file:///Users/parsa/dev/personal/java-projects/gel-event-driven-microservices/config-server-repository
          uri: https://github.com/Parsa-Sedigh/gel-event-driven-microservices-spring-cloud-config-repository
          clone-on-start: true
          username: Parsa-Sedigh
          password: x
      #          default-label: main # when we're using git, this would be name of the git branch

      # if config server can't reach the config server repo and load the config, it will stop immediately.
      fail-fast: true
  security:
    #    user:
    #      name: 123
    #      password: ENC(SJqPr1mrH+MihDeGt1FTNNojX8QyqXJqgE7u4rEx/PhdWim8IaLRtSEV2mQu/ZDN)
    user:
      name: 123
      password: 123

#jasypt:
#  encryptor:
#    # the password used for encrypting. In playground service, we used standardPBEStringEncryptor.setPassword() for this.
#    password: ${JASYPT_ENCRYPTOR_PASSWORD}